# Info about you
name: Marshall Johnson
position: Data Scientist III
email: mpj747@gmail.com
company_name: Expedia Group
company_url: https://www.expedia.com
place_name: Austin, TX

# Blog info
title: Marshall's Blog
description: Blog
url: https://marshallj27.github.io/Marshall27.github.io/
main_github_io: false
long_description: >-
    Welcome! I'm a data scientist 
# Social links
github_url: https://github.com/MarshallJ27
linkedin_url: http://www.linkedin.com/in/your-name
social:
  links:
    - http://www.linkedin.com/in/datamarsh
    - https://github.com/MarshallJ27

# Images + files
logo: IMG_1925.JPG
cv_url: assets/files/cv.pdf
#resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: light  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: 2b422b
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_background: 232
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38
